INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (1, 'Blazers', 'Portland', 'Oregon');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (2, 'Nuggets', 'Denver', 'Colorado');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (3, 'Warriors', 'Oakland', 'California');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (4, 'Rockets', 'Houston', 'Texas');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (5, 'Lakers', 'Los Angeles', 'California');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (6, 'Raptors', 'Toronto', 'Ontario');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (7, 'Celtics', 'Boston', 'Massachusetts');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (8, 'Spurs', 'San Antonio', 'Texas');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (9, 'Heat', 'Miami', 'Florida');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (10, 'Cavaliers', 'Cleveland', 'Ohio');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (11, '76ers', 'Philadelphia', 'Pennsylvania');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (12, 'Bucks', 'Milwaukee', 'Wisconsin');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (13, 'Thunder', 'Oklahoma City', 'Oklahoma');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (14, 'Knicks', 'New York City', 'New York');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (15, 'Jazz', 'Salt Lake City', 'Utah');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (16, 'Nets', 'Brooklyn', 'New York');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (17, 'Clippers', 'Los Angeles', 'California');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (18, 'Bulls', 'Chicago', 'Illinois');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (19, 'Mavericks', 'Dallas', 'Texas');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (20, 'Pistons', 'Detroit', 'Michigan');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (21, 'Magic', 'Orlando', 'Florida');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (22, 'Kings', 'Sacramento', 'California');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (23, 'Pacers', 'Indianapolis', 'Indiana');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (24, 'Timberwolves', 'Minneapolis', 'Minnesota');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (25, 'Suns', 'Phoenix', 'Arizona');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (26, 'Pelicans', 'New Orleans', 'Louisiana');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (27, 'Hornets', 'Charlotte', 'North Carolina');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (28, 'Hawks', 'Atlanta', 'Georgia');
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (29, 'Wizards', 'Washington D.C.', NULL);
INSERT INTO Bet.Teams (Id, Name, City, State) VALUES (30, 'Grizzlies', 'Memphis', 'Tennessee');
